AdminUsers:
    type: entity
    table: admin_users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        password:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        name:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
