imports:
    - { resource: config.yml }

doctrine:
    dbal:
        dbname:   "my_ecommerce_test"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Twig Configuration
twig:
    debug:            false
    strict_variables: false

# Assetic Configuration
assetic:
    debug:          false

# Doctrine Configuration
doctrine:
    orm:
        auto_generate_proxy_classes: false
        entity_managers: