# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      Website\WebBundle\Entity\Users:
        algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        pdo_mysql:
          entity:
            class: WebBundle:Users
            property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: pdo_mysql
            logout: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
              use_referer: false
              login_path: login
              check_path: login
              success_handler: login_success_handler
            logout:
              path: /logout
              target: /
    role_hierarchy:
      ROLE_CLIENT:      ROLE_USER
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]
