root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /shop/Developer
        permanent: true
web_shop:
    path:     /shop/{slug}
    defaults: { _controller: WebBundle:Default:index }
shop_product:
    path:     /shop/{categ}/{prodid}
    defaults: { _controller: WebBundle:Product:Product }
login:
    path:     /login
    defaults: { _controller: WebBundle:Login:login }
admin:
  path:       /admin
  defaults: { _controller: WebBundle:admin:admin }
clients:
  path:       /clients
  defaults: { _controller: WebBundle:Clients:clients }
logout_page:
    path:   /logout
    defaults:  { _controller: WebBundle:Logout:logout }
signup_page:
  path:  /signup
  defaults: { _controller: WebBundle:Signup:signup }
basket:
  path:  /basket
  defaults: { _controller: WebBundle:Basket:basket }
export_csv:
  path:  /orders/export/csv
  defaults: { _controller: WebBundle:CSVExport:ExportCSV }
export_json:
  path:  /orders/export/json
  defaults: { _controller: WebBundle:JSONExport:ExportJSON }
admin_users:
  path: /admin/users
  defaults: { _controller: WebBundle:adminUsers:adminUsers}
admin_webset:
  path: /admin/websettings
  defaults: { _controller: WebBundle:adminWebset:adminWebset}
admin_profile:
  path: /admin/profile
  defaults: { _controller: WebBundle:adminProfile:adminProfile}